#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$(which pt 2>/dev/null || true)" ]]; then
    return 0
  fi

  return 1
}

main "$@"
